apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- training-job-patch.yaml
resources:
- ../../base
images:
- name: ghcr.io/kimjunil/cifar_classifier
  newTag: 0.0.16
- name: ghcr.io/kimjunil/cifar_classifier_bento
  newTag: 0.0.1
