apiVersion: batch/v1
kind: Job
metadata:
  name: cifar-train-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: cifar-classifier
        image: ghcr.io/kimjunil/cifar_classifier:0.0.1
        args: ["--epochs", "1"]
        env:
        - name: WEB_HOOK_URL
          valueFrom:
            secretKeyRef:
              name: slackbot
              key: web_hook_url

      restartPolicy: Never