apiVersion: batch/v1
kind: Job
metadata:
  name: cifar-train-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: cifar-classifier
        image: ghcr.io/kimjunil/cifar_classifier:0.0.1
        args: ["--epochs", "1"]

      restartPolicy: Never
    
      nodeSelector:
        #<labelname>:value
        cloud.google.com/gke-nodepool: gpu-pool